name = "EchogramPyPlot"
uuid = "cefffc6e-22df-5efe-a096-e879be851ea5"
authors = ["Rob Blackwell <rob@robblackwell.com>"]
repo = "https://github.com/EchoJulia/EchogramPyPlot.jl.git"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
EchogramColorSchemes = "7aaf5238-35e9-11e9-344d-235b218e62a0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

